import Head from "next/head";
import axios from "axios";
import { allPostsQuery } from "../utils/queries";
import client from "../utils/client";
import VideoCard from "../components/VideoCard";
import NoResults from "../components/NoResults";

export default function Home({ videos }) {
  return (
    <div className="flex flex-col gap-10 videos h-full">
      <Head>
        <title>Tik Tik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {videos.length ? (
        videos.map((video) => <VideoCard key={video._id} post={video} />)
      ) : (
        <NoResults text={"No Videos"} />
      )}
    </div>
  );
}

export async function getServerSideProps(context) {
  // const response = await axios.get(`${process.env.URL}/api/post`);
  const query = allPostsQuery();

  const data = await client.fetch(query);
  return {
    props: { videos: data }, // will be passed to the page component as props
  };
}
